export * from './account.service';
import { AccountService } from './account.service';
export * from './configuration.service';
import { ConfigurationService } from './configuration.service';
export * from './employeeServices.service';
import { EmployeeServicesService } from './employeeServices.service';
export * from './founderServices.service';
import { FounderServicesService } from './founderServices.service';
export * from './leaveRequestServices.service';
import { LeaveRequestServicesService } from './leaveRequestServices.service';
export * from './leaveTypeServices.service';
import { LeaveTypeServicesService } from './leaveTypeServices.service';
export * from './managerServices.service';
import { ManagerServicesService } from './managerServices.service';
export * from './role.service';
import { RoleService } from './role.service';
export * from './session.service';
import { SessionService } from './session.service';
export * from './tenant.service';
import { TenantService } from './tenant.service';
export * from './tokenAuth.service';
import { TokenAuthService } from './tokenAuth.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AccountService, ConfigurationService, EmployeeServicesService, FounderServicesService, LeaveRequestServicesService, LeaveTypeServicesService, ManagerServicesService, RoleService, SessionService, TenantService, TokenAuthService, UserService];
