/**
 * EmployeeLeave API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeaveStatus } from './leaveStatus';


export interface ApproveLeaveDto { 
    employeeId?: number;
    approved_by_ID?: number;
    requestId?: number;
    status?: LeaveStatus;
}
export namespace ApproveLeaveDto {
}


