/**
 * EmployeeLeave API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeeResponseDto } from './employeeResponseDto';


export interface EmployeeResponseDtoListApiResponse { 
    status?: boolean;
    statusCode?: number;
    message?: string | null;
    data?: Array<EmployeeResponseDto> | null;
}

