/**
 * EmployeeLeave API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeDto { 
    id?: number;
    firstName: string;
    lastName: string;
    email: string;
    department?: string | null;
    dateOfJoining: string;
}

