/**
 * EmployeeLeave API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';


export interface EmployeeResponseDto { 
    id?: number;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    department?: string | null;
    isAppliedForEmployeeForManager?: boolean;
    isApprovedByFounder?: boolean;
    dateOfJoining?: string;
    user?: UserDto;
}

