/**
 * EmployeeLeave API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeaveRequestCreateUpdateDto } from './leaveRequestCreateUpdateDto';


export interface LeaveRequestCreateUpdateDtoApiResponse { 
    status?: boolean;
    statusCode?: number;
    message?: string | null;
    data?: LeaveRequestCreateUpdateDto;
}

