/**
 * EmployeeLeave API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeaveStatus } from './leaveStatus';


export interface LeaveRequestCreateUpdateDto { 
    id?: number;
    employeeId?: number;
    leaveTypeId?: number;
    fromDate?: string;
    toDate?: string;
    founder_Id_approved_rejected_BY?: number | null;
    reason?: string | null;
    status?: LeaveStatus;
}
export namespace LeaveRequestCreateUpdateDto {
}


