/**
 * EmployeeLeave API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ManagerDto { 
    id?: number;
    userId?: number;
    dateOfJoining?: string;
    work_experince_year?: number;
    isActive?: boolean;
    isApproved_by_Founder?: boolean;
}

