/**
 * EmployeeLeave API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagerResponseDto } from './managerResponseDto';


export interface ManagerResponseDtoListApiResponse { 
    status?: boolean;
    statusCode?: number;
    message?: string | null;
    data?: Array<ManagerResponseDto> | null;
}

